on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule: [cron: "16 */24 * * *"]

jobs:
  build-and-simulate:
    name: Build and Simulate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Run
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator
          export PROJ_PATH=$(pwd)
          cd .. && git clone https://github.com/SpinalHDL/SpinalCrypto.git && cd SpinalCrypto && sbt publishLocal && cd $PROJ_PATH
          ./run.sh
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
